### ISSUE TITLE
Evaluate the architecture of the plugin

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#10]
See issue otrv4/libotr-ng#114 of libotr-ng.

**Comment by juniorz** [comment]
- [ ] Remove the need for a "protocol_name" and "account_name" in libotr-ng. This is required by libotr, but we can provide a compatibility layer and remove this from libotr-ng.
- [ ] Revisit the mapping between PurpleAccount and otrng_client_s.

**Comment by olabini** [comment]
What is missing here?

**Comment by claucece** [comment]
I guess nothing. Closing it.
