### ISSUE TITLE
Crash by segmentation fault on fingerprints

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#102]
When going to the 'Configure plugin' dialog and to the 'Known fingerprints' tab, when clicking over any account, pidgin crashes by segmentation fault. This should not happen as you should be able to click on the account and start a conversation/verify from there. Seems to be introduced by the fingerprint work.. what do you think @olabini ?

**Comment by olabini** [comment]
Ah yeah. I'll take a look - I'm sure it's my fault.

**Comment by olabini** [comment]
But yeah, keep in mind that the fingerprint work is not done yet.

**Comment by claucece** [comment]
Awesome! Thanks :)

**Comment by olabini** [comment]
I've fixed the crash here. The full functionality is not really there yet for the fingerprint list though - I expect to do that when I finish up with all the v3 stuff as well, so I'm closing this.
