### ISSUE TITLE
OSX: Package 'libffi', required by 'gobject-2.0', not found

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#104]
Currently, I can't run `./configure` as it says: 

`OSX: Package 'libffi', required by 'gobject-2.0', not found`. By doing 

`export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/`, it works again.

Unsure if this is local, if the homebrew formula was broken, etc; but I opened it here for reference.

**Comment by olabini** [comment]
Yes, this is the same problem we had with the CoyIM build on OS X Travis. Something seems to have changed with the libffi package, or something with brew. Not sure. We can't do anything about it though, so my recommendation is that we put this information in the README and close this issue.

**Comment by claucece** [comment]
Isolating this, this is related to the newer formula of glib in Homebrew (2.60).

**Comment by lotuc** [comment]
https://github.com/mesonbuild/meson/issues/2273#issuecomment-420412230

This works.

**Comment by claucece** [comment]
Yes, the same, when I use `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"` it works. When working on this I noticed that if I switch the glib version to an older one (2.56.1), everything works correctly. @lotuc

**Comment by evandrix** [comment]
well, you _were_ warned:

```
$ brew info libffi
libffi: stable 3.2.1 (bottled), HEAD [keg-only]
Portable Foreign Function Interface library
https://sourceware.org/libffi/
/usr/local/Cellar/libffi/3.2.1 (16 files, 296.8KB)
  Poured from bottle on 2019-01-14 at 03:51:17
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libffi.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

==> Analytics
install: 120,865 (30 days), 367,289 (90 days), 1,244,416 (365 days)
install_on_request: 3,645 (30 days), 10,974 (90 days), 39,185 (365 days)
build_error: 0 (30 days)
```

**Comment by claucece** [comment]
Yes, @evandrix ... that was noted, but for older versions that was not needed. I think that is why people got confused ;)

**Comment by tourdownunder** [comment]
> `OSX: Package 'libffi', required by 'gobject-2.0', not found`. By doing
> 
> `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/`, it works again.

I had this issue while trying `pip install pycairo` and this solution worked perfectly except I had to let autocomplete find a newer version of libffi

``` shell
export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/
```

**Comment by shiv1m** [comment]
I am facing the same issue, Package 'libffi', required by 'gobject-2.0', not found MACOS-10.12.6 Sierra #113 

Tried both export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig",
export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/

Not working for me. I am using node version 12.7.0

**Comment by pkkr** [comment]
> I am facing the same issue, Package 'libffi', required by 'gobject-2.0', not found MACOS-10.12.6 Sierra #113
> 
> Tried both export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig",
> export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/
> 
> Not working for me. I am using node version 12.7.0

Sam issue not fixed by adding the export

**Comment by claucece** [comment]
Hey!

This library is not about the brew formula or libffi. Were those logs shown when trying to run this library @shiv1m @pkkr ?

Thanks!

**Comment by jimmyromanticdevil** [comment]
> Yes, the same, when I use `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"` it works. When working on this I noticed that if I switch the glib version to an older one (2.56.1), everything works correctly. @lotuc

I fIxed by brew install libffi and adding export PKG_CONFIG_PATH .
