### ISSUE TITLE
Review Test Case Fingerprint authentication

### ISSUE THREAD

**Issue by MauroVelasco** [otrv4/pidgin-otrng#105]
Some steps were not possible to verify:

`Remove all published values in prekey server` (didn't find where we can check that)

`Ensure that a new message saying "The privacy status of the current conversation is now:Private" has appeared in your window` (doesn't show)

`Click "Start private conversation"`  (doesn't show)
`Ensure that "Private conversation started." is written in the conversation window`
`Ensure that the "Authenticate buddy" options is not available on the "OTR" menu, but the "Reauthenticate buddy" option is`

`Ensure that the "Start private conversation","Verify fingerprint" and "Forget fingerprint" buttons are enabled` (Only "Verify fingerprint is enabled")

**Comment by claucece** [comment]
Hey!

> Remove all published values in prekey server (didn't find where we can check that)

You remove the keys folder in the docker prekey server. 

> Ensure that a new message saying "The privacy status of the current conversation is now:Private" has appeared in your window

Yeah, this seems to have been deleted. I'll check. 

> Click "Start private conversation" (doesn't show)
> Ensure that "Private conversation started." is written in the conversation window
> Ensure that the "Authenticate buddy" options is not available on the "OTR" menu, but the 
> "Reauthenticate buddy" option is

Does show up for me. Can you recheck?

> Ensure that the "Start private conversation","Verify fingerprint" and "Forget fingerprint" buttons are enabled (Only "Verify fingerprint is enabled")

Does show up for me. Can you recheck?


Thanks!
