### ISSUE TITLE
Review Test Case Publication

### ISSUE THREAD

**Issue by MauroVelasco** [otrv4/pidgin-otrng#106]
The following steps were not possible to verify:

```
Ensure that you see (in the console output)
* "Prekey Server: we have 0 prekey messages stored." two times
* "Prekey Server: Publishing prekey messages." two times
* "Prekey Server: received success" two times
```

**Comment by MauroVelasco** [comment]
The following messages don't appear:

`BOB_ITAG (upper case)`

`ALICE_ITAG(upper case)
`

**Comment by MauroVelasco** [comment]
The following messages don't appear:

```
Ensure that you see (in the console output)
* "Prekey Server: we have 100 prekey messages store." two times`
* TODO:this should trigger a publication of the client profile, but since this isn't done yet, we don't know that the output should be
```

**Comment by claucece** [comment]
Hey! I have updated the test and ensure that the messages are happening. They are indeed showing up now. 

> BOB_ITAG (upper case)
> ALICE_ITAG(upper case)

Not a message, but rather the name of a file.

Thanks!

**Comment by claucece** [comment]
@MauroVelasco @peterpalau can you check that it shows up for you as well?
