### ISSUE TITLE
Annoying message appear every time a message is sent or received 

### ISSUE THREAD

**Issue by peterpalau** [otrv4/pidgin-otrng#108]
Every time (almost) a receive or send a message, the following text appear in the conversation window:

```
The privacy status of the current conversation is now: Private | Not private
```

This affects the conversation making it annoying.

**Comment by peterpalau** [comment]
This is an example of how it appears:

![Screenshot from 2019-06-18 15-25-57](https://user-images.githubusercontent.com/12257885/59717356-6fbd7d00-91dd-11e9-8eb7-b51ae707b8b2.png)

**Comment by claucece** [comment]
Yeah.. for some reason, it appears every time. We need to fix that.

**Comment by peterpalau** [comment]
Ok, this is work to do.

**Comment by claucece** [comment]
I have reviewed the code and UI. The only problem I see is that prior to starting a OTR conversation this shows up: `The privacy status of the current conversation is: Not Private`. It should only show when an OTR conversation happens or stops... I think ;)
