### ISSUE TITLE
Give more information around what the privacy status means

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#110]
As discussed with @peterpalau , it will be good to give a proper explanation to users around what the privacy status means (for example, the status `The privacy status of the current conversation is: Not Private`). Maybe a pop up or an information show when the user scrolls over it.

**Comment by claucece** [comment]
Hey @peterpalau ,  I looked at the tooltip and seems usable for the case. This might be helpful:
https://stackoverflow.com/questions/8222890/gtk-showing-a-label-when-mouse-is-hovering-on-a-button and https://developer.gnome.org/gtk3/stable/GtkTooltip.html

**Comment by claucece** [comment]
So, I see that the "link" shows now the info. What it is missing then is only the text that shows up when the mouse is scrolled over? Thanks for the work!

**Comment by peterpalau** [comment]
> So, I see that the "link" shows now the info. What it is missing then is only the text that shows up when the mouse is scrolled over?

Yes,  I need to find a way to do it.

> Thanks for the work!

My pleasure. :+1:

**Comment by claucece** [comment]
Closing this ;)
