### ISSUE TITLE
Create an authors page

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#111]
This pertains creating a section (can be a dialog in the about) where the authors are listed.

**Comment by MauroVelasco** [comment]
Hi @claucece, this is the about screen, please take a look:

![Logo OTR](https://user-images.githubusercontent.com/2516223/64650886-da014a80-d3e5-11e9-8d28-00f6a5669c69.png)

**Comment by claucece** [comment]
@MauroVelasco It looks nice, but the font should be the same.. Can you maybe push the code? Thanks!

**Comment by MauroVelasco** [comment]
Hi @claucece, oky, I updated the font and uploaded the code.

![logo_redondo_otr2](https://user-images.githubusercontent.com/2516223/64654863-1043c780-d3f0-11e9-956e-232419fde7d8.png)

**Comment by claucece** [comment]
Hi, @MauroVelasco !

Looks nice! On my mac, it looks like this though:

<img width="782" alt="Screen Shot 2019-09-13 at 12 07 21 PM" src="https://user-images.githubusercontent.com/8270508/64854964-19ff4200-d61f-11e9-87eb-7d3e5ea35c90.png">

Maybe check if that the border is never shown. ;)

**Comment by MauroVelasco** [comment]
Hi @claucece, in Ubuntu don't show that border, I'll try in a MAC

**Comment by MauroVelasco** [comment]
Hi @claucece, the issue has been fix on Mac

<img width="782" alt="Screen Shot 2019-09-19 at 9 38 06 AM" src="https://user-images.githubusercontent.com/2516223/65254561-1c9be480-dac2-11e9-8162-42777a6ed7de.png">

**Comment by claucece** [comment]
Hi @MauroVelasco !

For some reason for me on MacOS.. the text of the website is not selectable...

**Comment by MauroVelasco** [comment]
Hi @claucece, oky I'll check asap
