### ISSUE TITLE
Interact with a prekey server

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#12]

**Comment by juniorz** [comment]
Apparently `libpurple` does not provide a public API that allows to interact with the XMPP protocol. A private API is available, but can only be used by plugins that are built in the same source tree as pidgin (look at the `pidgin/plugins` folder inside pidgin repo) .

We may need to get in contact with people from the pidgin project and ask for help.

In the meantime, I will continue the investigation by ignoring the service discovery and hardcoding our test server.

**Comment by claucece** [comment]
Mmmm.. 

> We may need to get in contact with people from the pidgin project and ask for help.

Let me see what we can do on that. 

> In the meantime, I will continue the investigation by ignoring the service discovery and hardcoding our test server.

Thanks!

**Comment by olabini** [comment]
I think this issue is resolved now - we implemented XMPP specific parts for the service discovery, and then used generic sending/receiving for the actual prekey communication.
