### ISSUE TITLE
Decide how to implement polices and modes 

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#15]
See issues otrv4/libotr-ng#66 and otrv4/libotr-ng#14 of libotr-ng.

**Comment by claucece** [comment]
See the comments on issue: otrv4/libotr-ng#66

**Comment by olabini** [comment]
As mentioned in the above referenced issue, we will not implement different modes in libotr-ng and pidgin-otrng. The basic support for policies will be implemented in libotr-ng, while the configuration of these policies will be done from inside the plugin.

**Comment by claucece** [comment]
Yes! I'm closing this one :) @olabini
