### ISSUE TITLE
Should we use the same license of libotr-ng?

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#2]

**Comment by claucece** [comment]
@olabini what do you think?

**Comment by juniorz** [comment]
The license must be GPL compatible (because of libprple).

> The way that plugins work in Libpurple causes them to fall in the "derivative" category and consequently MUST be released under a GPL compatible license. To be clear, this requirement means that plugins that use libraries with incompatible licenses MUST NOT be distributed (even if they use dynamic linking).

See https://developer.pidgin.im/wiki/Scripting%20and%20Plugins#Aretherelicensingrestrictionsonplugins:

**Comment by claucece** [comment]
Well, the GNU LGPL version 3 is compatible with GPLv3: https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses . But  LGPLv3 is not compatible with GPLv2 by itself. Maybe just choose GPL as well?

**Comment by juniorz** [comment]
I'll summarize the situation.

The current code of `libotr-ng` is a derivative work on `pidgin-otr` which is released under the "version 2 of the GNU General Public License" (GPLv2).

It depends on `libotr-ng` which is released under the "version 3 or later of the GNU Lesser General Public License" (LGPLv3 or later).

Quoting the link:

> Please note that LGPLv3 is not compatible with GPLv2 by itself. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well.

The current license in `pidgin-otr` DOES NOT explicitly says "GPLv2 or later" (and by the way the same applied to `libotr`).

So I went to look at this table (https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) to see our options.

For `pidgin-otrng`, we "want to copy code under GPLv2 only" (pidgin-otr) and we "want to use a library under LGPLv3 or later" (libotr-ng). We can chose any of these to license it:

- GPLv2 or later
- LGPLv2.1 only
- LGPLv2.1 or later

For `libotr-ng`, we "want to license our code under LGPLv3 or later" and we may have "copied code under GPLv2 only" (`libotr`). We also "want to use a library under GPLv2 only" (`libotr`). By the table, this is incompatible! We may need to license libotr-ng under "LGPLv2.1 or later".

Changing `libotr` and `pidgin-otr` to "GPLv2 or later" should probably fix this incompatibility.

I am assuming that, for `libotr-ng`, the "ISC license" (`libsodium`) and the "MIT license" (`libgoldilocks`) are compatible with our "LGPLv3 or later".

I am also assuming that the following dependencies are already compatible with both "GPLv2 or later" (for `libotr` and `pidgin-otr`) and "LGPLv3 or later" (for `libotr-ng`):

- libgcrypt
- glib-2.0
- gtk+-2.0
- libpidgin
- libpurple

**Comment by olabini** [comment]
OK, so the decision we have on this after the call with the OTR peeps:
- libotr-ng can be any license really. We will keep it as LGPL 3.0 (or later).
- pidgin-otrng is strongly derived from pidgin-otr. We have no choice here. We will keep the license for pidgin-otrng as GPL 2.0 (only)

**Comment by olabini** [comment]
The remaining work is to update the code base to have the proper statements everywhere, and adding the OTR developers as the copyright holders.

**Comment by claucece** [comment]
Thanks @olabini
