### ISSUE TITLE
When pidgin-otrng plugin is enabled, OTRv3 plugin crashes

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#20]

**Comment by juniorz** [comment]
It could be because they have symbols with the same name, but it is also unexpected how (and if) they should work when they are both enabled at the same time.

**Comment by olabini** [comment]
Honestly, I think OTRv4 should detect on plugin load whether OTRv3 is activated. If it is, we should display a warning dialog, telling the user to disable v3 and then restart.

**Comment by claucece** [comment]
Thanks! @olabini

**Comment by olabini** [comment]
Np. Simple, and nice. =)
