### ISSUE TITLE
Read and Write persistent state

### ISSUE THREAD

**Issue by juniorz** [otrv4/pidgin-otrng#26]
We are missing to read/write from/to a file:

- [x] Client profile
- [x] Prekey profile
- [x] Shared prekey
- [x] Prekey messages

See: `otrng_plugin_init_userstate()`

**Comment by olabini** [comment]
@giovaneliberato  - is this the one you're working on?

**Comment by giovaneliberato** [comment]
@olabini I finished the reading of prekeys. I'm thinking about started the other ones as things are fresh in my mind.

what do you thinki @claucece?

**Comment by giovaneliberato** [comment]
working on the prekey profile

**Comment by claucece** [comment]
Thanks @giovaneliberato I think the shared prekey does not make sense.. I'm putting this on the things to discuss on the next meeting.

**Comment by claucece** [comment]
@giovaneliberato I finished writing and reading the shared prekey. I guess the only thing missing here is to test the client profile reading.

**Comment by claucece** [comment]
@giovaneliberato I added the missing test for the prekey profile. We can close this now.
