### ISSUE TITLE
Multiple "OTR" menus in the Conversation window

### ISSUE THREAD

**Issue by juniorz** [otrv4/pidgin-otrng#29]
![image](https://user-images.githubusercontent.com/30809/42635274-0152ddca-85bc-11e8-9337-e9b8cd00d323.png)

I remember I had done the following:

- Started pidgin with pidgin-otrng enabled.
- Had a OTRv4 conversation.
- Finished the OTRv4 conversation.
- Disable pidgin-otrng, enabled pidgin-otr.
- Receive a query message from the other participant and started a OTRv3 conversation.

**Comment by juniorz** [comment]
And some of the duplicated menus crash the plugin when clicked.

**Comment by claucece** [comment]
Yeah.. I've seen this also happening.. does this happen when using v3 as well? or when having v4 and v3?

**Comment by claucece** [comment]
Needs to test if it is still happening.

**Comment by olabini** [comment]
Has anyone seen this issue the last months?

**Comment by claucece** [comment]
I haven't tried it..

**Comment by claucece** [comment]
I haven't seen it. Closing this.
