### ISSUE TITLE
Define which README to translate and which information goes to each one

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#3]

**Comment by olabini** [comment]
And not translate README.

**Comment by olabini** [comment]
What was the reason for us having both `README` and `README.md` initially? The `README` file is empty, but there was a reason we couldn't delete it, right?

**Comment by claucece** [comment]
Well, the problem is:

if you remove the readme, autotools will complain: 'Makefile.am: error: required file './README' not found', as `AM_INIT_AUTOMAKE([-Wall -Werror])`, expects a README and other files. I had to pass `AM_INIT_AUTOMAKE([-Wall -Werror foreing])` to fix it. See:

> Among different projects, automake is used with different options and settings. Some of the most important projects have their own flavour settings supported by automake directly, as a single option, these are gnu (the default), cygnus (removed in automake 1.13), gnits and the final foreign which is meant as a "none of the above" option.

> The two main differences between the gnu and foreign flavours is that the former requires the presence of a number of files in the top-level of the projects, such as NEWS, COPYING, AUTHORS, ChangeLog, README. Often enough, at least the first file in this list is just touch-ed to stop automake from failing.

https://autotools.io/automake/options.html#automake.options.flavors

Do you think the change is enough? @olabini

**Comment by olabini** [comment]
Hmm, interesting. Well, the other choice would be to just keep `README` and delete the `README.md` - I don't care _that_ much about having the .md extension.

**Comment by claucece** [comment]
I mean.. we are also using the `foreign` option in libotr-ng because of this reasons. The reason why people wanted the .md file was so it rendered 'nicely'.

**Comment by olabini** [comment]
Ah, in that case that's fine with me =) Let's keep this solution. Although I don't care about it rendering 'nicely'... =)
