### ISSUE TITLE
Always refer as 'OTR nextgen'

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#46]
Since the the v3 plugin is called v4 and the v4 is called nextgen, let's always talk about 'OTR'(when in reference to v3) and 'OTR nextgen' (when in reference to v4).

**Comment by olabini** [comment]
We decided to skip this idea, and instead always just refer to it as "OTR"

**Comment by claucece** [comment]
Agreed. Only when it specifically refers to the plugin, it should be called 'otr-ng'.
