### ISSUE TITLE
Change buttons on conversation window

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#48]
Remove the duplicated button in the bottom of the chat, leaving only the status of the private conversation always showing.

**Comment by olabini** [comment]
We decided to not do this. Instead, we should remove the "graphical" button in the menu on top. Right now there are three OTR menus (the actual menu item, the icon to the right of the menu item, and the button in the bottom right corner). We should remove the icon to the right of the menu item, but not the button in the bottom right corner.

**Comment by peterpalau** [comment]
I think in some point, the graphic menu item that appears on top, was the first implementation, an after that was added the `OTR` menu on the same level. 

There are at least 3 functions called for building the graphic item, I remove them?

**Comment by peterpalau** [comment]
Deleting the graphic menu item from the top, the conversation window will appear like the following image:

![Screenshot from 2019-06-11 10-29-38](https://user-images.githubusercontent.com/12257885/59285673-f699b500-8c33-11e9-9c4a-1c509d769705.png)

**Comment by claucece** [comment]
Awesome! I'll check
