### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#53]
Sometimes when the UI actions are too fast (you log in and not wait for the publication, and immediately start an OTR conversation), the account is not found and this happens:

` No prekey client. `

The printing of the account gives:

` THE ACCOUNT `z??? `

Sometimes as well, the protocol and account are not found for writing the persistent files and this gets writen:

```
@<b2><8a><dd><ce>!?:(null)
AAAABAABG4LpCAACABCzsG9HGCbEqD5hSHddu76Mu8Ol9NKhqAkXJyMoTVHFjLczxxcfaqUVRxknERlZK9VLwxlqLLVfoAAABAAAAAMzNAAABQAAAABbpUkLfLmvgcxJ16sRJYAOKWlpIgtLXpBEbFdi/YLAayijC269LAQXpEP23U4YPZdBky9CXDRRNeSwXkmA2SPnbokGoA4xhCiMsQRIoe6jQsxFblCC8vef+sGtzUrYWQC9fPlyIWucTz10QN5usCZhv3kchTUA
```

Can it be a threading error?

**Comment by claucece** [comment]
cc. @olabini

**Comment by olabini** [comment]
I'll look into this. Did you add any debug-printing to see those statements?

**Comment by olabini** [comment]
Any idea where the specific places were printed that you saw?

**Comment by claucece** [comment]
Yes, immediately as you send the storage status message, and you get back that they are too low, and you try to publish:

https://github.com/otrv4/pidgin-otrng/blob/master/prekey-plugin.c#L98


Then this func does not get a prekey client:

https://github.com/otrv4/pidgin-otrng/blob/master/prekey-plugin.c#L274

And it fails here:

https://github.com/otrv4/pidgin-otrng/blob/master/prekey-plugin.c#L85


Around being incorrectly written in the persistent file, Idk when it happen, it just popped out.

**Comment by olabini** [comment]
I have not been able to reproduce this - I've added a large amount of printings all over the place to check for it, but it never happens for me...

**Comment by claucece** [comment]
@olabini I'll recheck this.. maybe it is something solved.

**Comment by olabini** [comment]
I just got a crash here:
                #4  0x00007fdd49b12654 get_domain_from_jid (pidgin-otrng.so)
                #5  0x00007fdd49b11c17 otrng_plugin_get_prekey_client (pidgin-otrng.so)
My guess is that this is from a missing PurpleAccount, so probably connected.

**Comment by olabini** [comment]
I've added some assertions to the pidgin-helpers file, to make sure all these invariants are always checked.

**Comment by claucece** [comment]
I'm quite uncomfortable on all of this refactorings, as it seems like a lot of functionality is getting broken. I'm unsure in which other places it is broken...

**Comment by olabini** [comment]
Sorry, not sure what you're talking about on this issue. I just added assertions to make it faster to see when something is broken.

**Comment by claucece** [comment]
Well, I'm talking in general. But let's talk about this on the call.

**Comment by olabini** [comment]
Have you seen this issue again?

**Comment by olabini** [comment]
OK, we haven't seen this issue for a long while. I'll close this issue now. In case it comes back we can reopen, but I don't think it will.
