### ISSUE TITLE
We should make sure that resources are not used for storing fingerprints

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#61]
See https://bugs.otr.im/plugins/pidgin-otr/issues/14

**Comment by claucece** [comment]
I think we don't have this.. but I could be wrong.

**Comment by olabini** [comment]
I'll double check, but I think it should be fine.

**Comment by olabini** [comment]
I've just checked it, and as far as I can tell, we always use the account field, which is normalized to never include resource information.
