### ISSUE TITLE
Check settings for OTR logging

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#66]
See https://bugs.otr.im/plugins/pidgin-otr/issues/99 and https://bugs.otr.im/plugins/pidgin-otr/issues/80

**Comment by MauroVelasco** [comment]
A test case was done, considering the following for the option (Don't log OTR conversations) :

![dont_log_otr_conversation](https://user-images.githubusercontent.com/2516223/62954611-4ff99e00-bdb5-11e9-88f8-ea6ef5ab4957.png)

   Local Pidgin A_____________Remote Pidgin B
   uncheck__________________uncheck
   uncheck__________________check
   check____________________uncheck 
   check____________________check

In all scenarios the conversation was saved/unsaved according the configuration done. I believe we must close this issue, as didn't find a error scenario.

**Comment by claucece** [comment]
Ok. I have tested as well. It is working correctly. Closing this ;)
