### ISSUE TITLE
Be careful sending account name in the clear

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#70]
See https://bugs.otr.im/plugins/pidgin-otr/issues/140

**Comment by claucece** [comment]
So, this issue refers not when any query message is sent; but rather when it is received and you cannot  process it. 

In pidgin plugin with OTRv3, this then is shown:

```
?OTRv23? alice@localhost/ has requested an Off-the-Record private conversation.  However, you do not have a plugin to support that. See https://otr.cypherpunks.ca/ for more information.
```

We don't have an error message like that, so we only show:

```
?OTRv34?
```

We sometime in the past, talked about adding an error message of the type: `Failed to start an Off-the-Record private conversation.`.. is it something to add?

**Comment by claucece** [comment]
So, I added an appropriate message for the query message now. I have found other error messages that send the account name in the clear.. should we stop them as well? @olabini

**Comment by olabini** [comment]
Yes, I think so.

**Comment by claucece** [comment]
Ok, so the error messages that we send over the wire do not have the account name. However, notifications shown on the conversation window have.. should we remove that?

**Comment by olabini** [comment]
Hmm, so the notifications are only local, right? In that case it shouldn't be a problem to keep the account names in there. It's only for sending over the wire I want us to be careful.

**Comment by claucece** [comment]
Yeah, only local @olabini .. then, awesome.. I'll close the issue, as we don't send it over the wire anymore.
