### ISSUE TITLE
Remove the "what's this?" button when clicking on the "Not private" button in the Pidgin IM part

### ISSUE THREAD

**Issue by DrWhax** [otrv4/pidgin-otrng#71]
Currently, (same for pidgin-otr) we have an dialog option (What's this?) that opens https://otr.cypherpunks.ca/help/0.0.1/levels.php?lang=en

We decided to get rid of this in pidgin-otr so let's also remove it for pidgin-otrng! :)

**Comment by claucece** [comment]
This is removed now and changed for a 'Understanding OTRv4' dialog, that currently looks like this:

<img width="482" alt="screen shot 2018-12-20 at 10 51 56 am" src="https://user-images.githubusercontent.com/8270508/50295101-51044680-0445-11e9-8b93-87ea600d66a7.png">

We need content for it ;)

**Comment by DrWhax** [comment]
@claucece Cool! Thanks for that. I was thinking, maybe like this?

**What is OTRv4?**
OTRv4 is the fourth generation of the off-the-record protocol. If you want to know more about OTR, please visit; https://otr.im/otrv4.html.

That would be a page on the revamped OTR website.

**Comment by olabini** [comment]
Ah, that's nice! Except... The whole point is to avoid links completely.

**Comment by claucece** [comment]
Now looking like this: 
<img width="419" alt="screen shot 2018-12-21 at 6 40 31 pm" src="https://user-images.githubusercontent.com/8270508/50367701-fb689080-054f-11e9-9481-4f35341b48bf.png">

**Comment by peterpalau** [comment]
This is working now. Is there something else to do?

**Comment by claucece** [comment]
Yeah, I think this is done. Closing this.
