### ISSUE TITLE
Unable to start any offline conversation

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#77]
Right now, it is not possible to start an offline conversation. I always says:

```
Prekey Server: there are no prekey in storage for the requested recipient.
```

even if there are prekey ensembles. This might be due to the recent refactorings.

**Comment by claucece** [comment]
cc./ @giovaneliberato @olabini

**Comment by olabini** [comment]
I'll take a look at this tonight or tomorrow morning.

**Comment by olabini** [comment]
OK, so this is what I do with the latest code:
- Make sure the keys-directory for the prekey server is empty
- Make sure all otr4 files in `~/.purple` are gone
- Both `bob` and `alice` are enabled
- I start Pidgin with `--debug`
- Alice FAILS with her publishing - the prekey server says "invalid prekey profile in publication message"
- Bob on the other hand succeeds in publishing
- I disable Bob
- I then try to start an offline converstation from Alice to Bob. This fails with the same message @claucece reports above

So we probably have two different problems here.

**Comment by olabini** [comment]
I'm tracking another problem in otrv4/libotr-ng#162
The prekey profile problem is that _SOMETIMES_ the instance tag sent is wrong...

**Comment by claucece** [comment]
For me, it does not fail on publishing; but later it is not found.

**Comment by olabini** [comment]
Strange

**Comment by olabini** [comment]
Well, I can't investigate that until I know why the instance tag is sometimes wrong when publishing...

**Comment by claucece** [comment]
I'll try again with the newest changes. I've tried going to older changes but I can't as the refactorings have been all over the place at different times..

**Comment by olabini** [comment]
Ah ok, thanks.

**Comment by claucece** [comment]
Ok, so I managed to start and offline conversation by managing to publish things. Most of the times though, it is impossible to publish as the b proof is wrong.

**Comment by claucece** [comment]
Ok, so I actually cannot manage to start an offline conversation. The same `Prekey Server: there are no prekey in storage for the requested recipient.` appears.

**Comment by olabini** [comment]
So, it seems the instance tags sometimes go wrong in the prekey profile, because there seems to be a confusion between the two instances for alice and bob. Exactly how this happens isn't clear yet.

**Comment by claucece** [comment]
I'm unsure if this is the reason why the prekey ensembles are not found. Maybe that is the problem but this one seems bigger.

**Comment by olabini** [comment]
Would you mind trying again with all the latest stuff? I've fixed a few different things.

**Comment by claucece** [comment]
Still the same message.

**Comment by olabini** [comment]
OK, I'll see if I get it too

**Comment by olabini** [comment]
Yep, it happens for me too. I'll look into it.

**Comment by olabini** [comment]
OK, the reason why this happens is because we never actually receive a client profile to publish - so there are no complete ensembles.

**Comment by olabini** [comment]
OK, I've fixed this problem now - it was because of the thing around when publication of prekey profiles and client profiles should happen not working. I disabled it so that these will always publish for the moment.

Please try it out.

**Comment by claucece** [comment]
Working now, thanks @olabini
