### ISSUE TITLE
Manage the Client Profile

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#8]
See where it will be published, if the serialization is ok, how it will be published and retrieved. 

See issue otrv4/libotr-ng#108 of libotr-ng.

Tasks
- [x] Create and publish a client profile if there's none
- [x] Create a new client profile and publish after expiration
- [x] Update and publish the existing client profile if one of the values changes

**Comment by claucece** [comment]
On this we should include as well:

- [ ] Check when reading a client profile that it is signed by the same private key that we have also read. Change it and publish new one if it changed.

**Comment by claucece** [comment]
cc. @giovaneliberato

**Comment by giovaneliberato** [comment]
I stopped working on this until #72 is done. This will give us a single place to manage all the cases listed above.

**Comment by olabini** [comment]
All done.
