### ISSUE TITLE
Should we have the dialog when generating the private key?

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#83]
So, for some reasons, the dialog showing up when generating the key was causing problems. I've temporarily disabled it. We should decide if we want to keep it. There are a few things that makes this weird:

- If there is little randomness, generating the key can take time
  - But generating an ed448 key is MUCH faster than a DH key
- If the generation takes time, it will freeze the UI
  - But, we are using ed448 keys during the DAKE as well, so if the long-term key takes a long enough time to generate that it freezes the UI, we can face the same problem when starting a conversation
- We also generate a forging key - should we show two dialogs? One for both of them?

Thoughts on this?

**Comment by claucece** [comment]
I've always found the dialog weird as it gives no valuable information to the user. I'll find much more weird if we also have a dialog for the forging key. I'll say: let's have no dialogs.

**Comment by olabini** [comment]
Ping @DrWhax

**Comment by DrWhax** [comment]
I don't like dialogs either, the user probably doesn't know what it would mean anyway, except for the more technical one's, and those probably understand what's going on.

Let's see if we can spin these things in a seperate thread or something similar.

**Comment by claucece** [comment]
Ok. I guess the decision is remove. I think it has been removed now... right, @olabini ?

**Comment by olabini** [comment]
Yeah, it's gone.

**Comment by claucece** [comment]
Awesome! Let's close this.
