### ISSUE TITLE
Correct generation of persistent values

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#87]
We should test that:

* I delete all otrv4 files on the purple directory, 
* I delete persisted values on the prekey server
* I open pidgin with the otr-ng plugin enabled.
* I activate my account and enter my password (if needed)
* I successfully log in
* When I log in, the client profile, prekey profile, private key, forging key, prekey messages, fingerprints, and shared prekey file are correctly generated
* The prekey messages are correctly published (there no error at plugin nor server side), and are persisted on the server

**Comment by olabini** [comment]
This is now working as expected.
