### ISSUE TITLE
Manage the Prekey Profile

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#9]
See where it will be published, if the serialization is ok, how it will be published and retrieved. 

Tasks
- [x] Create and publish a prekey profile if there's none
- [x] Create a new prekey profile and publish after expiration
- [x] Update and publish the existing prekey profile if one of the values changes
- [ ] Update and publish if the corresponding client profile is updated

**Comment by claucece** [comment]
cc. @giovaneliberato

**Comment by giovaneliberato** [comment]
I stopped working on this until #72 is done. This will give us a single place to manage all the cases listed above.

**Comment by claucece** [comment]
Thanks @giovaneliberato

**Comment by olabini** [comment]
All of this is done, except for changing the prekey profile if the client profile changes - since these two values are independent we don't need to do that.
