### ISSUE TITLE
Ensure Fingerprint authentication test case works

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#92]
Ensure that the test case in https://github.com/otrv4/pidgin-otrng/wiki/Test-Case---Fingerprint-authentication works correctly. In the process of doing that, fill in the documentation in the wiki with more details where necessary.

**Comment by olabini** [comment]
The test case has been extended with more details. The whole fingerprint verification path works fine, except for #94.
Once @giovaneliberato or @claucece can review the Test case in the wiki, I propose we close this issue since #94 is tracked in that specific issue.

**Comment by claucece** [comment]
It has been reviewed.. closing this.

**Comment by olabini** [comment]
@claucece gave a thumbs-up on IRC, so I'm closing this now.

**Comment by olabini** [comment]
Jinx

**Comment by olabini** [comment]
We should have a segment testing the fingerprint verification part of the configuration dialog as well.

**Comment by olabini** [comment]
OK, this has been added to the test case
