### ISSUE TITLE
Stop printing messages with links

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#95]
We are sometimes giving the user messages that contain hyperlinks - we should stop doing that.

**Comment by olabini** [comment]
@claucece has been working on this one.

**Comment by claucece** [comment]
This is not completely finished as there are some messages still with links. This refers to the messages shown in the UI.

**Comment by peterpalau** [comment]
This includes anchor links with custom formats like `open://prefs` or `foo://`?

**Comment by claucece** [comment]
> This includes anchor links with custom formats like open://prefs or foo:// or only external links?

No. Only externals.

**Comment by peterpalau** [comment]
I think we can close this one because no more messages with links are printed in the actual version.

**Comment by claucece** [comment]
I think so too.. I have not seen any link printed anymore..I'll recheck tomorrow ;)

**Comment by claucece** [comment]
It has been checked. Closing it now.
