### ISSUE TITLE
Incorrectly assuming there is always going to be v3  files

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#97]
The code seems to imply that there is always going to be some v3 files (the private key): https://github.com/otrv4/pidgin-otrng/blob/master/plugin-all.c#L1885 Should we keep this?

**Comment by claucece** [comment]
I think this is now solved by the orchestration work that has been done. Now, we don't always assume there has to be v3 files, right? @olabini

**Comment by olabini** [comment]
Yeah, I think it should be fixed.

**Comment by claucece** [comment]
Awesome! thanks!
