### ISSUE TITLE
There should not be a way to start a conversation with yourself

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#98]
The fingerprint window will often show your own account with the ability of starting a conversation with it (in this case, alice):

<img width="798" alt="screen shot 2018-10-07 at 4 05 21 pm" src="https://user-images.githubusercontent.com/8270508/46585732-d71a0f00-ca4a-11e8-9815-42e2fb50eced.png">

When you try to do that, this shows up:

<img width="365" alt="screen shot 2018-10-05 at 7 59 23 pm" src="https://user-images.githubusercontent.com/8270508/46585734-e00ae080-ca4a-11e8-9c41-c76f00dda210.png">

We shouldn't allow the starting the conversation with oneself.

**Comment by olabini** [comment]
Just to clarify here, the problem is not really your OWN account. The problem is when you try to start a conversation FROM an account that is disabled or offline. We should just disable the button in this case.
