### ISSUE TITLE
Show the ssid

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#99]
The secure session ID (SSID) is a 8-byte value. It is used to to verify (over the telephone, assuming the parties recognize each others' voices) that there is no man-in-the-middle. it should be displayed in this way, as described in the protocol:

```
For example, in C language, in "%08x" format. If the party transmitted the Auth-R message during 
the DAKE, then display the first 4 bytes in bold, and the second 4 bytes in non-bold. If the party
transmitted the Auth-I message instead, display the first 4 bytes in non-bold, and the second 4 bytes
in bold. If the party transmitted the Non-Interactive-Auth message during the DAKE, then display the
first 4 bytes in bold, and the second 4 bytes in non-bold. If the party received the 
Non-Interactive-Auth message instead, display the first 4 bytes in non-bold, and the second 4 bytes 
in bold.
```

It should be somehow shown in the UI of the plugin.

**Comment by MauroVelasco** [comment]
Hi @claucece,

I'm showing the SSID in the following way:

![i99_1](https://user-images.githubusercontent.com/2516223/62159360-1e71d480-b2d7-11e9-9afa-fd8a6e911397.png)

And the information about SSID is shown in a dialog, when the user click on SSID link:

![i99_2](https://user-images.githubusercontent.com/2516223/62159454-67c22400-b2d7-11e9-93d6-736cb33cc54d.png)

Can we show the SSID in that way?

**Comment by claucece** [comment]
Awesome! Looks perfect!

**Comment by MauroVelasco** [comment]
Hi @claucece,

The final version as suggested looks like this:

![i99_3](https://user-images.githubusercontent.com/2516223/62232494-fabc9600-b38b-11e9-9678-afc1e08f2fad.png)

**Comment by claucece** [comment]
@MauroVelasco .. check that I did in the last commit ;)

**Comment by MauroVelasco** [comment]
Great, thks @claucece for the improvement

**Comment by MauroVelasco** [comment]
Hi @claucece,

The option to show/hide ssid info is:

![ss_config_show_ssid](https://user-images.githubusercontent.com/2516223/62571163-52f50b80-b856-11e9-9661-8a44ef4d9561.png)

Let me know if that location is fine

**Comment by peterpalau** [comment]
I would recommend this option to be `unchecked` by default and use a more intuitive name like:
```
[X] Show the SSID in the conversation window
```

**Comment by MauroVelasco** [comment]
This is the final screenshot of the configuration property.

![ss_config_show_ssid_2](https://user-images.githubusercontent.com/2516223/62658152-abe3a300-b92d-11e9-9a04-b037f6bef83b.png)

**Comment by claucece** [comment]
Perfect! Closing this ;)
